os: linux
dist: trusty
language: python
python: "3.6"
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - make
      - binutils

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - conan install . --build=missing
  - cmake .
  - make
  - ctest
